schema_version = 0
kind = "audio-steward"
piece = "evo-device-audio"
version = "0.1.13"
target = "aarch64-unknown-linux-gnu"
binaries = ["evo-device-audio"]
built_at = "2026-09-08T19:42:22Z"
publisher = "org.evoframework"
git_rev = "c1b6dbf532405ad6108a45d8b3b9caeb6638e98d"
