schema_version = 0
publisher = "org.evoframework"
channel = "dev"
updated_at = "2026-09-09T08:15:47Z"

[[pointers]]
piece = "evo-device-audio"
version = "0.1.13"

[[pointers]]
piece = "org.evoframework.artwork.local"
version = ""

[[pointers]]
piece = "org.evoframework.artwork.online"
version = ""

[[pointers]]
piece = "org.evoframework.audio.terminus"
version = ""

[[pointers]]
piece = "org.evoframework.composition.alsa"
version = ""

[[pointers]]
piece = "org.evoframework.delivery.alsa"
version = ""

[[pointers]]
piece = "org.evoframework.hardware.audio-config"
version = ""

[[pointers]]
piece = "org.evoframework.metadata.local"
version = ""

[[pointers]]
piece = "org.evoframework.multiroom.evo-native"
version = ""

[[pointers]]
piece = "org.evoframework.network"
version = ""

[[pointers]]
piece = "org.evoframework.playback.mpd"
version = ""

[[pointers]]
piece = "org.evoframework.playback.options"
version = ""

[[pointers]]
piece = "org.evoframework.system.power"
version = ""

