schema_version = 0
kind = "audio-steward"
piece = "evo-device-audio"
version = "0.1.13.0"
target = "aarch64-unknown-linux-gnu"
binaries = ["evo-device-audio"]
built_at = "2026-09-23T12:33:01Z"
publisher = "org.evoframework"
git_rev = "6f302c96eed27cbe38e85182cf357427028f68ee"
