schema_version = 0
kind = "audio-dist"
piece = "evo-device-audio-dist"
version = "0.1.13.0"
built_at = "2026-09-23T12:21:27Z"
publisher = "org.evoframework"
git_rev = "6f302c96eed27cbe38e85182cf357427028f68ee"
