schema_version = 0
kind = "kiosk-session"
piece = "evo-kiosk"
version = "0.1.13.0"
built_at = "2026-09-23T13:33:03Z"
publisher = "org.evoframework"
git_rev = "d97579044e042a505005668e44d5d7a3e3c5d102"
