schema_version = 0
kind = "distribution-bundle"
version = "0.1.13"
cut = "v0.1.13.0"
publisher = "org.evoframework"
release_url = "https://github.com/foonerd/evo-device-audio-artefacts/releases/tag/v0.1.13.0"
download_base = "https://github.com/foonerd/evo-device-audio-artefacts/releases/download/v0.1.13.0"

[[assets]]
target = "x86_64-unknown-linux-gnu"
name = "evo-device-audio-x86_64-unknown-linux-gnu-0.1.13.tar.gz"
sha256 = "f17a56abda3aa7539b3d5a57180c0ff96585db17d990377a50b321f743d5a57f"
size = 121128439

[[assets]]
target = "aarch64-unknown-linux-gnu"
name = "evo-device-audio-aarch64-unknown-linux-gnu-0.1.13.tar.gz"
sha256 = "e565ae025975515a691fb17fbce94fbb81f538ad07305883ecddc6f12ae116c0"
size = 115655412

[[assets]]
target = "armv7-unknown-linux-gnueabihf"
name = "evo-device-audio-armv7-unknown-linux-gnueabihf-0.1.13.tar.gz"
sha256 = "9a0d51c1694877cf249fdaf56bbe09125676ab9b2f868c944f8037189b239be8"
size = 117145449

