schema_version = 0
kind = "distribution-bundle"
version = "0.1.13"
cut = "v0.1.13.0"
publisher = "org.evoframework"
release_url = "https://github.com/foonerd/evo-device-audio-artefacts/releases/tag/v0.1.13.0"
download_base = "https://github.com/foonerd/evo-device-audio-artefacts/releases/download/v0.1.13.0"

[[assets]]
target = "x86_64-unknown-linux-gnu"
name = "evo-device-audio-x86_64-unknown-linux-gnu-0.1.13.tar.gz"
sha256 = "0c69411918aa2b11c7dc5ed69beb12c6bbbe40b8dbf18d2e267bce4f25af947a"
size = 121542900

[[assets]]
target = "aarch64-unknown-linux-gnu"
name = "evo-device-audio-aarch64-unknown-linux-gnu-0.1.13.tar.gz"
sha256 = "0f986854d82f4b8c81a05724fc54b3f583445243c17c1af8a54d5dbb997d56ce"
size = 116076229

[[assets]]
target = "armv7-unknown-linux-gnueabihf"
name = "evo-device-audio-armv7-unknown-linux-gnueabihf-0.1.13.tar.gz"
sha256 = "b26bae10b9b7bb56fefa42a6335a1fb785610c735a5bd27279c4635272e284e1"
size = 117616928

