schema_version = 0
kind = "distribution-bundle"
version = "0.1.13"
cut = "v0.1.13.0"
publisher = "org.evoframework"
release_url = "https://github.com/foonerd/evo-device-audio-artefacts/releases/tag/v0.1.13.0"
download_base = "https://github.com/foonerd/evo-device-audio-artefacts/releases/download/v0.1.13.0"

[[assets]]
target = "x86_64-unknown-linux-gnu"
name = "evo-device-audio-x86_64-unknown-linux-gnu-0.1.13.tar.gz"
sha256 = "5e5ca2be27db3e00052a8207709cd71e9447ccd814a1f20340ef20243eafd6ab"
size = 121128575

[[assets]]
target = "aarch64-unknown-linux-gnu"
name = "evo-device-audio-aarch64-unknown-linux-gnu-0.1.13.tar.gz"
sha256 = "6d35e30aea2e9540548ff1b25f9ea8697a4b98df4865aa3a38c6ca892d0a6078"
size = 115655765

[[assets]]
target = "armv7-unknown-linux-gnueabihf"
name = "evo-device-audio-armv7-unknown-linux-gnueabihf-0.1.13.tar.gz"
sha256 = "34c3d0b34986ebce712485da6c13ebdd29d14c5b2327f8c31d5cfda0c72d5f81"
size = 117145603

