schema_version = 0
kind = "audio-steward"
piece = "evo-device-audio"
version = "0.1.13"
target = "armv7-unknown-linux-gnueabihf"
binaries = ["evo-device-audio"]
built_at = "2026-09-12T20:48:56Z"
publisher = "org.evoframework"
git_rev = "4db2bb89f9acd00aca2b2a54f55c087f60c5e9a0"
